frontend/public/index.html, frontend/src/components/default_styling/style.css, frontend/src/components/splash/splash.css, frontend/src/components/splash/splash.jsx
- Also figured out a color scheme which I commented in style.css
=> Finished A Rough Splash Page

Game Logic/board.js, Game Logic/player.js, Game Logic/point.js
=> GameLogic +

frontend/src/components/game/game.css, frontend/src/components/game/game_board/game_board_button.jsx
Added a console.log to print out the row and col the button is on
=> functioning handle click

Game Logic/board.js
=> Game Logic

frontend/src/actions/modal_action.js, frontend/src/actions/session_actions.js, frontend/src/components/app.jsx, frontend/src/components/general_purpose_icons/close_icon.jsx, frontend/src/components/login/demo_login_button.jsx, frontend/src/components/login/login.jsx, frontend/src/components/nav_bar/drop_down/user_drop_down_option.jsx, frontend/src/components/nav_bar/drop_down/user_drop_down_options.jsx, frontend/src/components/nav_bar/logged_in_options.jsx, frontend/src/components/nav_bar/logged_out_options.jsx, frontend/src/components/nav_bar/login_button.jsx, frontend/src/components/nav_bar/login_button_container.js, frontend/src/components/nav_bar/logout_button.jsx, frontend/src/components/nav_bar/logout_button_container.jsx, frontend/src/components/nav_bar/modal.js, frontend/src/components/nav_bar/nav_bar.css, frontend/src/components/nav_bar/nav_bar.jsx, frontend/src/components/nav_bar/right_nav_bar_items.jsx, frontend/src/components/nav_bar/right_nav_bar_items_container.js, frontend/src/components/nav_bar/sign_up_button.jsx, frontend/src/components/nav_bar/sign_up_button_container.js, frontend/src/components/root.js, frontend/src/components/sign_up/sign_up.css, frontend/src/components/sign_up/sign_up.jsx, frontend/src/components/sign_up/sign_up_container.jsx, frontend/src/components/splash/splash.jsx, frontend/src/reducers/modals_reducer.js, frontend/src/reducers/root_reducer.js, frontend/src/reducers/ui_reducer.js, frontend/src/util/session_utils.js
I still have to implement the actions to work with the backend. I also have to implement a close button but currently the modals can be closed by clicking on the gray background.
=> rough login/signUp modals

app.js, config/passport.js, models/User.js, routes/api/users.js, validation/login.js, validation/register.js, validation/valid-text.js
=> Register/Login User

frontend/src/actions/game_action.js, frontend/src/components/game/game.jsx, frontend/src/components/game/game_board/gameBoard_Container.js, frontend/src/components/game/game_board/game_board.jsx, frontend/src/components/game/game_board/game_board_button.jsx, frontend/src/components/game/game_container.js, frontend/src/reducers/entities_reducer.js, frontend/src/reducers/games_reducer.js, frontend/src/reducers/root_reducer.js, frontend/src/util/game_util.js, routes/api/games.js
Progress on Go Board Front End Redux and React
=> Board Redux and Views

app.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/chat_box/chat_box.jsx, package-lock.json, package.json
Simple websockets working which show when a new user connects to the page
=> Working websockets

app.js, frontend/src/components/chat_box/chat_box.jsx
Updates react state with message sent with websockets
=> Chat functionality

frontend/src/actions/game_action.js, frontend/src/components/game/game.jsx, frontend/src/components/game/game_board/gameBoard_Container.js, frontend/src/components/game/game_board/game_board.jsx, frontend/src/components/game/game_container.js, frontend/src/reducers/games_reducer.js, frontend/src/reducers/session_reducer.js, frontend/src/util/game_util.js, frontend/src/util/session_api_util.js
=> FrontEndBoard

frontend/package-lock.json, frontend/package.json, frontend/src/actions/game_action.js, frontend/src/components/game/game.jsx, frontend/src/components/game/game_board/gameBoard_Container.js, frontend/src/components/game/game_board/game_board.jsx, frontend/src/reducers/games_reducer.js
=> FrontEndBoardReact&Redux

frontend/src/actions/game_action.js, frontend/src/components/game/game.jsx, frontend/src/components/game/game_board/gameBoardButton_Container.js, frontend/src/components/game/game_board/gameBoard_Container.js, frontend/src/components/game/game_board/game_board.jsx, frontend/src/components/game/game_board/game_board_button.jsx, frontend/src/reducers/chat_reducer.js, frontend/src/reducers/games_reducer.js, frontend/src/util/game_util.js, routes/api/games.js
=> Game Patch working

frontend/src/components/game/GameLogic/game.js, frontend/src/components/game/GameLogic/point.js, frontend/src/components/game/game.jsx, frontend/src/components/game/game_board/gameBoardButton_Container.js, frontend/src/components/game/game_board/game_board.jsx, frontend/src/components/game/game_board/game_board_button.jsx
Commented out some stuff. should render app fine now.
=> Commented Out some stuff in GameLogic

frontend/src/components/splash/splash.jsx, frontend/src/components/splash/splash_container.jsx
Will open login modal before if user is not logged in and trying to create a game
=> Improved create game functionality

frontend/src/components/app.jsx, frontend/src/components/lobby/lobby.jsx, frontend/src/components/lobby/lobby_container.js, frontend/src/components/splash/splash.jsx, frontend/src/index.js
Now routes to a specific lobby and game page for a specific game instance instead of being sent to a general game page
=> Frontend routes working properly

frontend/src/components/chat_box/chat_box.css, frontend/src/components/chat_box/chat_box.jsx, frontend/src/components/lobby/lobby.jsx
- Press enter to send a chat message
- Sending many chat messages leads to the view becoming scrollable instead of going beyond box
=> Improved Chat

frontend/src/actions/game_action.js, frontend/src/components/splash/lobby_rows/lobby_row.jsx, frontend/src/components/splash/lobby_rows/lobby_rows.jsx, frontend/src/components/splash/lobby_rows/lobby_rows_container.js, frontend/src/components/splash/splash.jsx, frontend/src/components/splash/splash_container.js, frontend/src/reducers/games_reducer.js
Shows index of all games
Still needs to limit games shown to active games
Still needs to have a working join game button
=> Rough index page

frontend/src/components/default_styling/style.css, frontend/src/components/splash/splash.jsx, frontend/src/components/splash/splash_container.js
- Changed data to add in current user to players instead of default data
- Reversed order of lobby games so the most recent is on top
=> Simple updates

frontend/src/components/default_styling/style.css, frontend/src/components/splash/lobby_rows/lobby_rows.jsx
=> CSS improvement - tiny change

config/passport.js, frontend/src/index.js, package.json, routes/api/users.js
When refreshing user information persisted with local storage
=> Saves user between refreshes

frontend/src/components/game/game.css, frontend/src/components/game/game.jsx, frontend/src/components/game/game_board/gameBoard.jsx, frontend/src/components/game_settings/game_settings.jsx, frontend/src/components/nav_bar/logged_in_options.jsx, frontend/src/components/nav_bar/logged_in_options_container.js, frontend/src/components/nav_bar/modal.js, frontend/src/components/splash/lobby_rows/lobby.css, frontend/src/components/splash/splash.jsx
- Removed lobby view
- Rough modal done for game settings
- offsets updated for game board
=> Removing Lobby View

frontend/src/components/game/game_board/gameBoard.jsx, frontend/src/components/nav_bar/logged_in_options.jsx
Fix bug: Going back to lobby page gets rid of game settings button
=> Game Settings Bug Fix

frontend/src/components/chat_box/chat_box.jsx
Work on getting author data to show up with chat messages
=> Partial chat improvement

frontend/src/components/game/game.jsx, frontend/src/components/game_settings/gameSettings.jsx, frontend/src/components/nav_bar/logged_in_options.jsx, frontend/src/components/nav_bar/modal.js, frontend/src/components/splash/lobby_rows/lobby_row.jsx
- Removed Game Settings Button
- Fixed Player Count for lobbies on Splash Page
- Closes modal when making new game
=> UI updates
